-- 003_seed_data.sql
-- Seed default admin user and equipment data
-- Password for admin: 'admin123' (SHA-256 hash with salt, generated by application)
-- This insert uses a pre-computed hash; the auth module must produce the same format.
-- Hash format: salt:hex_digest  (salt=fabui_salt)

-- Default admin user
-- The password hash will be inserted by the seed script using the Julia auth module.
-- For now, insert a placeholder that the seed script will update.
INSERT INTO users (username, password_hash, role)
VALUES ('admin', 'PLACEHOLDER_RUN_SEED_SCRIPT', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Equipment seed data (matches frontend mock data)
INSERT INTO equipment (name, description, area, bay, status, criticality, updated_by, last_comment) VALUES
    ('E-Beam Lithography System', 'Electron Beam Writer', 'Lithography', 'Bay 1A', 'UP', 'Critical', 'admin', 'Calibration complete'),
    ('RIE Plasma Etcher', 'Reactive Ion Etcher', 'Etching', 'Bay 2B', 'UP WITH ISSUES', 'High', 'operator', 'RF power fluctuating'),
    ('PECVD Chamber A', 'Plasma CVD System', 'Deposition', 'Bay 3A', 'MAINTENANCE', 'Medium', 'admin', 'Scheduled PM in progress'),
    ('Wafer Prober Station', 'Electrical Test System', 'Metrology', 'Bay 4C', 'DOWN', 'Critical', 'operator', 'Stage motor failure'),
    ('Sputter Deposition Tool', 'PVD Magnetron Sputter', 'Deposition', 'Bay 3B', 'UP', 'Low', 'admin', 'Running batch 47'),
    ('Optical Profilometer', 'Surface Metrology', 'Metrology', 'Bay 4A', 'UP', 'Medium', 'operator', 'Ready for use')
ON CONFLICT DO NOTHING;
